package:
    name: gdam
    version: "1.2.4"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - cc-plugin-glider
        - compliance-checker
        - gutils >=1.2.6
        - pyinotify
        - pymongo
        - python
        - pyzmq

test:
    requires:
        - pytest
    imports:
        - gdam
        - gdam.nc
        - gdam.cli
        - gdam.processor
    commands:
        - gdam-cli -h
        - gdam2nc -h
        - nc2ftp -h

about:
    home: https://github.com/axiom-data-science/GDAM
    license: MIT License
    license_file: LICENSE
    summary: Watches a directory for new *db flight/science files, inserts the data into a MongoDB instance, and publishes the data to a ZeroMQ socket.
